
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: loki
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: #link#
      chart: loki
      targetRevision: #version#

      helm:
        valueFiles:
          - $values/platform/logging/loki/values.yaml

    - repoURL: https://github.com/Ramzan9000/EKS-V1-gitops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
      
    syncOptions:
      - CreateNamespace=true

# incomplete need to just get the helm chart and its version from the webiste #